# PART TWO (Population in States and geofile)

In [5]:
import pandas as pd
import geopandas as gpd

#### 1- Read the geojson file

In [6]:
gdf = gpd.read_file("south-sudan-with-regions_.geojson")
gdf

,id,name,density,path,geometry
0,11471,Central Equatoria,0,/world/South Sudan/Central Equatoria,"MULTIPOLYGON (((32.27351 4.79651, 32.26687 4.8..."
1,11470,Eastern Equatoria,0,/world/South Sudan/Eastern Equatoria,"MULTIPOLYGON (((35.94423 4.61914, 35.93833 4.6..."
2,11476,Jonglei,0,/world/South Sudan/Jonglei,"MULTIPOLYGON (((35.02196 6.43453, 35.02166 6.4..."
3,11474,Lakes,0,/world/South Sudan/Lakes,"MULTIPOLYGON (((31.60613 5.99364, 31.59494 6.0..."
4,11469,Northern Bahr el Ghazal State,0,/world/South Sudan/Northern Bahr el Ghazal State,"MULTIPOLYGON (((28.03912 9.34789, 27.85675 8.9..."
5,11472,Unity State,0,/world/South Sudan/Unity State,"MULTIPOLYGON (((30.93877 9.52865, 30.86651 9.5..."
6,11477,Upper Nile State,0,/world/South Sudan/Upper Nile State,"MULTIPOLYGON (((34.14552 9.03281, 34.13041 9.2..."
7,11475,Warrap,0,/world/South Sudan/Warrap,"MULTIPOLYGON (((29.67500 8.33275, 29.66464 8.4..."
8,11478,Western Bahr el Ghazal State,0,/world/South Sudan/Western Bahr el Ghazal State,"MULTIPOLYGON (((28.56355 7.35246, 28.53463 7.4..."
9,11473,Western Equatoria,0,/world/South Sudan/Western Equatoria,"MULTIPOLYGON (((30.90056 5.60748, 30.87933 5.6..."

In [7]:
gdf.rename({'name': 'state'}, axis=1, inplace=True)

In [8]:
gdf

,id,state,density,path,geometry
0,11471,Central Equatoria,0,/world/South Sudan/Central Equatoria,"MULTIPOLYGON (((32.27351 4.79651, 32.26687 4.8..."
1,11470,Eastern Equatoria,0,/world/South Sudan/Eastern Equatoria,"MULTIPOLYGON (((35.94423 4.61914, 35.93833 4.6..."
2,11476,Jonglei,0,/world/South Sudan/Jonglei,"MULTIPOLYGON (((35.02196 6.43453, 35.02166 6.4..."
3,11474,Lakes,0,/world/South Sudan/Lakes,"MULTIPOLYGON (((31.60613 5.99364, 31.59494 6.0..."
4,11469,Northern Bahr el Ghazal State,0,/world/South Sudan/Northern Bahr el Ghazal State,"MULTIPOLYGON (((28.03912 9.34789, 27.85675 8.9..."
5,11472,Unity State,0,/world/South Sudan/Unity State,"MULTIPOLYGON (((30.93877 9.52865, 30.86651 9.5..."
6,11477,Upper Nile State,0,/world/South Sudan/Upper Nile State,"MULTIPOLYGON (((34.14552 9.03281, 34.13041 9.2..."
7,11475,Warrap,0,/world/South Sudan/Warrap,"MULTIPOLYGON (((29.67500 8.33275, 29.66464 8.4..."
8,11478,Western Bahr el Ghazal State,0,/world/South Sudan/Western Bahr el Ghazal State,"MULTIPOLYGON (((28.56355 7.35246, 28.53463 7.4..."
9,11473,Western Equatoria,0,/world/South Sudan/Western Equatoria,"MULTIPOLYGON (((30.90056 5.60748, 30.87933 5.6..."

#### 2- Read the Population file

In [9]:
Population =pd.read_excel('population.xlsx')
Population

                     name      2008     2010     2017
0        Central Equatoria  1103557  1193130  1574711
1        Eastern Equatoria   906161   962719  1393765
2                  Jonglei  1358602  1228824  1873176
3                    Lakes   695730   782504  1053177
4  Northern Bahr el Ghazal   720898   920834  1023383
5                    Unity   585801   399105   875313
6               Upper Nile   964353  1013629  1385478
7                   Warrap   972928  1044217  1379960
8   Western Bahr el Ghazal   333431   358692   473636
9        Western Equatoria   619029   658863   803263

In [10]:
df = gdf.join(Population)

In [11]:
df

,id,state,density,path,geometry,name,2008,2010,2017
0,11471,Central Equatoria,0,/world/South Sudan/Central Equatoria,"MULTIPOLYGON (((32.27351 4.79651, 32.26687 4.8...",Central Equatoria,1103557,1193130,1574711
1,11470,Eastern Equatoria,0,/world/South Sudan/Eastern Equatoria,"MULTIPOLYGON (((35.94423 4.61914, 35.93833 4.6...",Eastern Equatoria,906161,962719,1393765
2,11476,Jonglei,0,/world/South Sudan/Jonglei,"MULTIPOLYGON (((35.02196 6.43453, 35.02166 6.4...",Jonglei,1358602,1228824,1873176
3,11474,Lakes,0,/world/South Sudan/Lakes,"MULTIPOLYGON (((31.60613 5.99364, 31.59494 6.0...",Lakes,695730,782504,1053177
4,11469,Northern Bahr el Ghazal State,0,/world/South Sudan/Northern Bahr el Ghazal State,"MULTIPOLYGON (((28.03912 9.34789, 27.85675 8.9...",Northern Bahr el Ghazal,720898,920834,1023383
5,11472,Unity State,0,/world/South Sudan/Unity State,"MULTIPOLYGON (((30.93877 9.52865, 30.86651 9.5...",Unity,585801,399105,875313
6,11477,Upper Nile State,0,/world/South Sudan/Upper Nile State,"MULTIPOLYGON (((34.14552 9.03281, 34.13041 9.2...",Upper Nile,964353,1013629,1385478
7,11475,Warrap,0,/world/South Sudan/Warrap,"MULTIPOLYGON (((29.67500 8.33275, 29.66464 8.4...",Warrap,972928,1044217,1379960
8,11478,Western Bahr el Ghazal State,0,/world/South Sudan/Western Bahr el Ghazal State,"MULTIPOLYGON (((28.56355 7.35246, 28.53463 7.4...",Western Bahr el Ghazal,333431,358692,473636
9,11473,Western Equatoria,0,/world/South Sudan/Western Equatoria,"MULTIPOLYGON (((30.90056 5.60748, 30.87933 5.6...",Western Equatoria,619029,658863,803263

In [12]:
df.rename({2008: 'Population in 2008', 2010: 'Population in 2010', 2017: 'Population in 2017' ,'state': 'State'}, axis=1, inplace=True)

In [13]:
df

,id,State,density,path,geometry,name,Population in 2008,Population in 2010,Population in 2017
0,11471,Central Equatoria,0,/world/South Sudan/Central Equatoria,"MULTIPOLYGON (((32.27351 4.79651, 32.26687 4.8...",Central Equatoria,1103557,1193130,1574711
1,11470,Eastern Equatoria,0,/world/South Sudan/Eastern Equatoria,"MULTIPOLYGON (((35.94423 4.61914, 35.93833 4.6...",Eastern Equatoria,906161,962719,1393765
2,11476,Jonglei,0,/world/South Sudan/Jonglei,"MULTIPOLYGON (((35.02196 6.43453, 35.02166 6.4...",Jonglei,1358602,1228824,1873176
3,11474,Lakes,0,/world/South Sudan/Lakes,"MULTIPOLYGON (((31.60613 5.99364, 31.59494 6.0...",Lakes,695730,782504,1053177
4,11469,Northern Bahr el Ghazal State,0,/world/South Sudan/Northern Bahr el Ghazal State,"MULTIPOLYGON (((28.03912 9.34789, 27.85675 8.9...",Northern Bahr el Ghazal,720898,920834,1023383
5,11472,Unity State,0,/world/South Sudan/Unity State,"MULTIPOLYGON (((30.93877 9.52865, 30.86651 9.5...",Unity,585801,399105,875313
6,11477,Upper Nile State,0,/world/South Sudan/Upper Nile State,"MULTIPOLYGON (((34.14552 9.03281, 34.13041 9.2...",Upper Nile,964353,1013629,1385478
7,11475,Warrap,0,/world/South Sudan/Warrap,"MULTIPOLYGON (((29.67500 8.33275, 29.66464 8.4...",Warrap,972928,1044217,1379960
8,11478,Western Bahr el Ghazal State,0,/world/South Sudan/Western Bahr el Ghazal State,"MULTIPOLYGON (((28.56355 7.35246, 28.53463 7.4...",Western Bahr el Ghazal,333431,358692,473636
9,11473,Western Equatoria,0,/world/South Sudan/Western Equatoria,"MULTIPOLYGON (((30.90056 5.60748, 30.87933 5.6...",Western Equatoria,619029,658863,803263

## Export the file as a Geojson

In [19]:
df.to_file('PopulationByStates.geojson')